#!/bin/env bash
echo -e "\e[1;32m Step 1: Upgrading your distro\n===============================\e[0m"
sudo apt-get dist-upgrade -y

echo

echo -e "\e[1;32m Step 2: Updating packages\n===========================\e[0m"
sudo apt-get update -y

echo

echo -e "\e[1;32m Step 3: Upgrading packages\n============================\e[0m"
sudo apt-get upgrade -y

echo

echo -e "\e[1;32m Step 4: Repair broken dependencies\n====================================\e[0m"
sudo apt-get check

echo

echo -e "\e[1;32m Step 5: Removing all the junk files\n=====================================\e[0m"
sudo apt-get clean -y
sudo apt-get autoclean -y
sudo apt-get autoremove -y

echo

echo -e "\e[1;32m \tCONGRATULATIONS!!\n \tYour system is clean and up-to-date\e[0m"

echo
