#!/bin/env bash

LOG_FILE="system_update.log"
exec > >(tee -i $LOG_FILE)
exec 2>&1

echo -e "\e[1;32m Step 1: Updating|Upgrading packages\n=====================================\e[0m"
sudo apt-get update -y && sudo apt-get upgrade -y || { echo "Update failed"; exit 1; }

echo

echo -e "\e[1;32m Step 2: Installing Security Updates\n====================================\e[0m"
sudo unattended-upgrade -d

echo

echo -e "\e[1;32m Step 3: Repair broken packages/dependencies\n=============================================\e[0m"
sudo apt --fix-missing update -y
sudo apt-get update -y
sudo apt-get install -f -y || { echo "Package fix failed"; exit 1; }

echo

echo -e "\e[1;32m Step 4: Removing all the junk files\n=====================================\e[0m"
sudo apt-get clean -y
sudo apt-get autoclean -y
sudo apt-get autoremove -y

echo

echo -e "\e[1;32m Step 5: Verifying package integrity\n=====================================\e[0m"
sudo debsums --all | grep -v OK

echo

echo -e "\e[1;32m Last step: Updating packages\n==============================\e[0m"
sudo apt-get update -y && sudo apt-get upgrade -y || { echo "Final update failed"; exit 1; }

echo

echo -e "\e[1;32m \tCONGRATULATIONS $USER!!\n \tYour system is clean and up-to-date\e[0m"

echo
